/// <reference  path="../../pb_data/types.d.ts" />

onBootstrap((e) => {
	e.next();
	console.log('Hello World!');
});

onRecordAfterUpdateSuccess((e) => {
	e.next();

	const APP_URL = 'https://amar-vote.pockethost.io';
	const icon = e.record!;
	if (!e.record) return;

	const candidateID = e.record!.get('assigned_to');

	try {
		if (candidateID.length == 0) return;

		const candidateInfo = $app.findRecordById('candidates', candidateID);
		const post = $app.findRecordById('posts', candidateInfo!.get('post'));

		const informationVerify = new MailerMessage({
			from: {
				address: $app.settings().meta.senderAddress,
				name: $app.settings().meta.senderName
			},
			to: [{ address: candidateInfo!.get('email') }],
			subject: `Welcome ${candidateInfo!.get('name')}! Your Candidacy Has Been Registered!`,
			html: /*html*/ `
			<h3>Dear ${candidateInfo!.get('name')},</h3>
			<p>We are pleased to inform you that your candidacy has been successfully registered in our system. Below are your details:</p>

			<p><strong>Candidate Name:</strong> ${candidateInfo!.get('name')}</p>
			<p><strong>Class:</strong> ${candidateInfo!.get('class')} - ${candidateInfo!.get('section')}</p>
			<p><strong>Position:</strong> ${post!.get('title')}</p>

			<p><strong>Candidate Image</strong><p>
			<img src="${APP_URL}/api/files/${candidateInfo.collection().id}/${candidateID}/${candidateInfo.get('image')}" alt="candidate-image" />

			<p><strong>Campaign Icon</strong><p>
			<img src="${APP_URL}/api/files/${icon.collection().id}/${icon.id}/${icon.get('icon')}" alt="icon-image" />

			<p>Please review your details and ensure that everything is correct. You can download your campaign icon on desktop by right clicking on it and selection "Save Image As". If you have any questions or require modifications, feel free to reach out to a member of the Student Elections Department</p>
			
			<p>We wish you the best of luck in the upcoming election!</p>

			<p><strong>Best regards,</strong></p>
			<p><strong>Student Elections Department, Chinmaya Vidyalaya CBSE</strong></p>

			<hr />

			<p style="color: rgb(40,40,40); text-align: center;">This email was automatically generated by AMAR Vote</p>
			<p style="color: rgb(40,40,40); text-align: center;">Made with ❤️ by <strong>Adarsh Ravikumar</strong> - Batch of 2025</p>
			`
		});

		const guidelines = new MailerMessage({
			from: {
				address: $app.settings().meta.senderAddress,
				name: $app.settings().meta.senderName
			},
			to: [{ address: candidateInfo!.get('email') }],
			subject: `📢 Campaign Guidelines for Candidates`,
			html: /*html*/ `
			<h3>Dear ${candidateInfo!.get('name')},</h3>
			<p>Congratulations on running for office in our school elections! To ensure a fair, respectful, and enjoyable campaign, please follow these guidelines:</p>

			<h4>✅ DOs: Run a Positive and Fair Campaign</h4>
			<ul style="list-decoration: none">
				<li> <strong>✔ Be Friendly & Respectful</strong> – Treat fellow candidates, voters, and school staff with kindness. </li>
				<li> <strong>✔ Stay Honest</strong> – Share your ideas truthfully. Avoid false promises or misleading statements. </li>
				<li> <strong>✔ Promote Your Strengths</strong> – Focus on what <strong>you</strong> can do for the school rather than criticizing others. </li>
				<li> <strong>✔ Encourage Participation </strong> – Inspire classmates to get involved and vote, regardless of who they support. </li>
				<li> <strong>✔ Follow School Rules</strong> – Stick to the guidelines for posters, speeches, and social media usage. </li>
				<li> <strong>✔ Be Inclusive</strong> – Represent all students and listen to their ideas with an open mind. </li>
			</ul>

			<hr style="opacity: 0.3"/>
			
			<h4>❌ DON'Ts: Avoid Negative or Unfair Tactics</h4>
			<ul style="list-decoration: none">
				<li><strong>❌ No Toxic Behavior</strong> – Avoid personal attacks, insults, or spreading rumors about other candidates.</li>
				<li><strong>❌ No Bribing or Pressuring Voters</strong> – Let students decide freely without offering rewards or forcing them.</li>
				<li><strong>❌ No Vandalism</strong> – Do not damage or remove another candidate’s posters or materials.</li>
				<li><strong>❌ No Spam Campaigning</strong> – Avoid excessive messaging, classroom interruptions, or pressuring students online.</li>
				<li><strong>❌ No Disrupting School Activities</strong> – Campaigning should not interfere with learning or school events.</li>
			</ul>
			
			<hr style="opacity: 0.3"/>

			<h4>⚖ Fair Play & Good Sportsmanship</h4>
			<ul>
				<li><strong>Win or Lose Gracefully</strong> – If you win, be humble. If you lose, support the winner and stay involved in school leadership.</li>
				<li><strong>Respect Election Results</strong> – The election process is free and fair; let’s keep it that way.</li>
			</ul>

			<p>This election is about leadership, responsibility, and teamwork. Make it a great experience for yourself and your school.</p>
			<p>We wish you the best of luck in the upcoming election!</p>

			<p><strong>Best regards,</strong></p>
			<p><strong>Student Elections Department, Chinmaya Vidyalaya CBSE</strong></p>

			<hr />

			<p style="color: rgb(40,40,40); text-align: center;">This email was automatically generated by AMAR Vote</p>
			<p style="color: rgb(40,40,40); text-align: center;">Made with ❤️ by <strong>Adarsh Ravikumar</strong> - Batch of 2025</p>
			`
		});

		console.log(`Email sent to ${candidateInfo!.get('email')}`);

		$app.newMailClient().send(informationVerify);
		$app.newMailClient().send(guidelines);
	} catch (e) {
		console.log('something went terribly wrong');
		console.log(e);
	}
}, 'icons');
